{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.home.mroz.shell;

  onePass =
    if pkgs.stdenv.hostPlatform.isLinux then
      { gpgProgram = lib.getExe' pkgs._1password-gui "op-ssh-sign"; }
    else if pkgs.stdenv.hostPlatform.isDarwin then
      { gpgProgram = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"; }
    else
      throw "Unsupported platform for the 1Password SSH signer";

  colors = config.lib.stylix.colors.withHashtag;

  yaml = pkgs.formats.yaml { };
in
{
  config = lib.mkIf cfg.enable {
    programs.git = {
      enable = true;
      ignores = [ "*.swp" ];
      signing = {
        signByDefault = true;
        key = cfg.identity.signingKey;
        format = "ssh";
        signer = onePass.gpgProgram;
      };
      settings = {
        alias = {
          lg = "log --stat";
          lgp = "log --stat -p";
          lgg = "log --graph";
          lgga = "log --graph --decorate --all";
          lgm = "log --graph --max-count 10";
          lo = "log --oneline --decorate";
          lgo = "log --oneline --decorate --graph";
          lgoa = "log --oneline --decorate --graph --all";
          lol = "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit";
          lola = "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all";

          # git-absorb turns a pile of working-tree fixes into fixup! commits
          # aimed at whichever commit introduced each hunk, then folds them in.
          # The stacked-branch equivalent of `git commit --amend`.
          ab = "absorb --and-rebase";

          # difftastic understands syntax, so it collapses reformatting and
          # rename noise that delta still shows as churn. Opt-in rather than
          # default because it is slower and useless for prose.
          dft = "!git -c diff.external=difft diff";
          dshow = "!git -c diff.external=difft show --ext-diff";
          dlog = "!git -c diff.external=difft log -p --ext-diff";
        };

        user = {
          name = cfg.identity.name;
          email = cfg.identity.gitEmail;
        };

        core = {
          editor = "vim";
          autocrlf = "input";
        };

        init.defaultBranch = "main";

        # Histogram is patience with better performance characteristics and
        # produces markedly more readable hunks on real code.
        diff = {
          algorithm = "histogram";
          colorMoved = "default";
          colorMovedWS = "allow-indentation-change";
          mnemonicPrefix = true;
          renames = true;
        };

        # zdiff3 keeps the common ancestor in conflict markers, which turns most
        # "which side do I want" questions into a three-way read.
        merge.conflictStyle = "zdiff3";

        # Remembers how a conflict was resolved and replays it. Pays for itself
        # the first time a stack gets rebased twice.
        rerere = {
          enabled = true;
          autoUpdate = true;
        };

        push = {
          autoSetupRemote = true;
          followTags = true;
        };

        fetch = {
          prune = true;
          pruneTags = true;
        };

        pull.rebase = true;

        rebase = {
          autoStash = true;
          autoSquash = true;
          # Rewrites the branches pointing into the middle of a stack when the
          # base is rebased, instead of orphaning them.
          updateRefs = true;
        };

        # Most recently touched branches first, which is almost always the
        # order you actually want to read them in.
        branch.sort = "-committerdate";
        tag.sort = "version:refname";

        column.ui = "auto";
        help.autocorrect = "prompt";
        commit.verbose = true;
        log.date = "iso";
        status.submoduleSummary = true;

        difftool = {
          prompt = false;
          difftastic.cmd = ''difft "$LOCAL" "$REMOTE"'';
        };
      };
      lfs.enable = true;
    };

    programs.delta = {
      enable = true;
      enableGitIntegration = true;
      options = {
        features = "decorations line-numbers side-by-side";
        # tmTheme generated by Stylix's bat target, which delta reads from
        # bat's theme cache.
        syntax-theme = "base16-stylix";
        whitespace-error-style = "22 reverse";
        decorations = {
          commit-decoration-style = "bold yellow box ul";
          file-style = "bold yellow ul";
          file-decoration-style = "none";
        };
      };
    };

    home.packages = with pkgs; [
      git-absorb
      difftastic
      gh-dash
    ];

    # gh-dash has no Stylix target, so paint it from the same palette by hand.
    # gh itself comes from Homebrew; gh-dash reads its credentials.
    xdg.configFile."gh-dash/config.yml".source = yaml.generate "gh-dash-config.yml" {
      prSections = [
        {
          title = "mine";
          filters = "is:open author:@me";
        }
        {
          title = "review";
          filters = "is:open review-requested:@me";
        }
        {
          title = "involved";
          filters = "is:open involves:@me -author:@me";
        }
      ];
      issuesSections = [
        {
          title = "created";
          filters = "is:open author:@me";
        }
        {
          title = "assigned";
          filters = "is:open assignee:@me";
        }
      ];
      defaults = {
        preview = {
          open = true;
          width = 70;
        };
        prsLimit = 20;
        issuesLimit = 20;
        prApproveComment = "LGTM";
      };
      theme = {
        ui.table.showSeparator = true;
        colors = {
          text = {
            primary = colors.base05;
            secondary = colors.base0D;
            inverted = colors.base00;
            faint = colors.base04;
            warning = colors.base09;
            success = colors.base0B;
          };
          background.selected = colors.base02;
          border = {
            primary = colors.base0D;
            secondary = colors.base02;
            faint = colors.base01;
          };
        };
      };
    };
  };
}
